{
 "title": "Turbine Streaming Metrics",
 "tags": [
  "kafka",
  "streaming",
  "wind"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "✅ Valid Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "turbine_messages_valid" }
   ]
  },
  {
   "title": "❌ Invalid Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "turbine_messages_invalid" }
   ]
  },
  {
   "title": "💾 DB Inserts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "turbine_db_inserts" }
   ]
  }
 ]
}