name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: turbine_user
          POSTGRES_PASSWORD: turbine_pass
          POSTGRES_DB: turbine_db
        options: >-
          --health-cmd="pg_isready -U turbine_user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r consumer/requirements.txt
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          flake8 consumer/ producer/

      - name: Run tests
        run: |
          pytest consumer/tests/
          pytest producer/tests/

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Consumer Image
        run: docker build -t consumer ./consumer

      - name: Build Producer Image
        run: docker build -t producer ./producer
